import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloClient, InMemoryCache, ApolloProvider, gql } from '@apollo/client';
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Apollo client instance to support querying GraphQL API
const client = new ApolloClient({
  uri: "https://indexer.bigdevenergy.link/9e37ca4/v1/graphql",
  cache: new InMemoryCache(),
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    {/*<ApolloProvider client={client}>*/}
      <body className={inter.className}>
        <NavBar>
          {children}
        </NavBar>
      </body>
    {/*</ApolloProvider>*/}
    </html>
  );
}
