import type { Metadata } from "next";
import React from "react";
import "@/styles/globalsDefault.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Header from "@/components/home/Header";
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";
import { WagmiProvider } from "wagmi";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

const queryClient = new QueryClient()
import { wagmiConfig } from '@/lib/wagmi/wagmiConfig';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <WagmiProvider config={wagmiConfig}>
          <QueryClientProvider client={queryClient}>
          <html lang="en">
      <body
          className={cn("min-h-screen bg-background font-sans antialiased",
          fontSans.variable
      )}
      >
      <Header />
      {children}
      </body>
    </html>
          </QueryClientProvider>
      </WagmiProvider>
  );
}
